# Generated by Django 6.0 on 2025-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='image',
            field=models.ImageField(blank=True, default='airport_images/default.jpg', null=True, upload_to='airport_images/'),
        ),
    ]
